"""Shared utilities for `sjh_learn`."""

from .checks import evaluate_sanity_checks, n2_mainline_equivalence_check
from .fields import (
    CarrierField,
    CarrierFieldPhysical,
    CodeCarrierField,
    CodeConstantDrive,
    CodeGaussianCarrierField,
    CodeGaussianDrive,
    CompositeField,
    CompositeLabFieldPhysical,
    ConstantDrive,
    ConstantRwaDrivePhysical,
    FieldConfig,
    GaussianCarrierField,
    GaussianCarrierFieldPhysical,
    GaussianDrive,
    GaussianRwaDrivePhysical,
    electric_field_array,
    electric_field_value,
    field_from_dict,
    make_rwa_drive_from_physical_field,
    total_electric_field_array,
    total_electric_field_value,
)
from .io import (
    QuantumResultIO,
    ResultManager,
    default_output_path,
    save_figure,
    save_parameter_summary,
    save_result_case,
    save_result_data,
    save_results_components_long,
)
from .model import build_c_ops, build_lab_hamiltonian, compute_detuning, compute_energy_gap
from .normalization import ParaNormalizer
from .observables import (
    chi_two_level_linear,
    dipole_expectation_D,
    polarization_C_per_m2,
)
from .parameters import (
    NLevelPhysicalParams,
    NLevelSolverParams,
    ParameterSweep,
    PhysicalParameterSweep,
    PureDephasingChannel,
    RelaxationChannel,
    SolverParams,
)
from .plotting import (
    build_preview_figure,
    plot_coherences,
    plot_density_components,
    plot_drive,
    plot_field,
    plot_multilevel_components,
    plot_populations,
)
from .results import DynamicsResult
from .solvers import (
    default_rwa_drive,
    make_rotating_view,
    optical_params_from_solver,
    rotate_density_trajectory,
    rotating_frame_unitary,
    run_case,
    run_lab_case,
    run_parameter_sweep,
    run_physical_case,
    run_physical_parameter_sweep,
    run_rwa_case,
    simulate_lab_frame,
    simulate_rwa_frame,
)

__all__ = [
    "DynamicsResult",
    "NLevelSolverParams",
    "NLevelPhysicalParams",
    "RelaxationChannel",
    "PureDephasingChannel",
    "SolverParams",
    "ParaNormalizer",
    "dipole_expectation_D",
    "polarization_C_per_m2",
    "chi_two_level_linear",
    "PhysicalParameterSweep",
    "ParameterSweep",
    "ConstantDrive",
    "GaussianDrive",
    "CarrierField",
    "GaussianCarrierField",
    "CompositeField",
    "CarrierFieldPhysical",
    "GaussianCarrierFieldPhysical",
    "CompositeLabFieldPhysical",
    "ConstantRwaDrivePhysical",
    "GaussianRwaDrivePhysical",
    "make_rwa_drive_from_physical_field",
    "CodeConstantDrive",
    "CodeGaussianDrive",
    "CodeCarrierField",
    "CodeGaussianCarrierField",
    "FieldConfig",
    "field_from_dict",
    "electric_field_value",
    "electric_field_array",
    "total_electric_field_value",
    "total_electric_field_array",
    "compute_detuning",
    "compute_energy_gap",
    "build_lab_hamiltonian",
    "build_c_ops",
    "QuantumResultIO",
    "ResultManager",
    "default_output_path",
    "save_result_data",
    "save_results_components_long",
    "save_figure",
    "save_result_case",
    "save_parameter_summary",
    "simulate_lab_frame",
    "simulate_rwa_frame",
    "rotating_frame_unitary",
    "rotate_density_trajectory",
    "optical_params_from_solver",
    "default_rwa_drive",
    "run_case",
    "run_lab_case",
    "run_physical_case",
    "run_parameter_sweep",
    "run_physical_parameter_sweep",
    "run_rwa_case",
    "make_rotating_view",
    "plot_field",
    "plot_drive",
    "plot_populations",
    "plot_coherences",
    "plot_density_components",
    "plot_multilevel_components",
    "build_preview_figure",
    "evaluate_sanity_checks",
    "n2_mainline_equivalence_check",
]
